name: pmiestimation
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - pillow==9.2.0
    - matplotlib==3.6.2
    - tqdm==4.64.1
    - scikit-learn==1.1.3
    - numpy==1.23.5
    - opencv-python==4.8.1.78
    - pandas==1.5.2
    - torch==1.13.0+cu116
    - torchvision==0.14.0+cu116
    - torchaudio==0.13.0
    - --extra-index-url https://download.pytorch.org/whl/cu116
